### PR TITLE
Only initiate backfill when it's enabled

### LINKED ISSUE #34: Don't attempt to backfill when backfill is disabled in the config
Currently the bridge starts backfilling after connecting to Slack, which doesn't work on synapse (yet).
The bridge should check if backfilling is enabled in the config file before it does this.

### PR DESCRIPTION
**Pull request by twouters**
Fixes #34

### CODE REVIEW

File: user.go [hunk 1]
```diff
@@ -410,11 +410,13 @@ func (user *User) slackMessageHandler(userTeam *database.UserTeam) {
 
 			user.log.Infofln("connected to team %s as %s", userTeam.TeamName, userTeam.SlackEmail)
 
-			portals := user.bridge.dbPortalsToPortals(user.bridge.DB.Portal.GetAllForUserTeam(userTeam.Key))
-			for _, portal := range portals {
-				err := portal.ForwardBackfill()
-				if err != nil {
-					user.log.Warnfln("Forward backfill for portal %s failed: %v", portal.Key, err)
+			if (user.bridge.Config.Bridge.Backfill.Enable) {
```
Comment (bradtgmurray) [inline user.go:413]: We should skip sending the `StateBackfilling` above as well

**Review by tulir — APPROVED** [review]
